"""
Configuration management for Sentry.

Handles loading, saving, and validating configuration thresholds
from a TOML file at ~/.config/sentry/config.toml.
"""

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore[no-redef]


@dataclass
class Config:
    """Configuration settings for Sentry hardware monitoring.

    Attributes:
        cpu_temp_threshold: CPU temperature alert threshold in Celsius (default: 70).
        gpu_temp_threshold: GPU temperature alert threshold in Celsius (default: 70).
        arm_voltage_min: Minimum ARM voltage threshold in V (default: 1.2).
        core_voltage_min: Minimum core voltage threshold in V (default: 1.2).
        config_path: Path to the configuration file.
    """

    cpu_temp_threshold: float = 70.0
    gpu_temp_threshold: float = 70.0
    arm_voltage_min: float = 1.2
    core_voltage_min: float = 1.2
    config_path: Optional[Path] = None

    def __post_init__(self) -> None:
        """Initialize config path if not provided."""
        if self.config_path is None:
            self.config_path = Path.home() / ".config" / "sentry" / "config.toml"

    @classmethod
    def load(cls, config_path: Optional[Path] = None) -> "Config":
        """Load configuration from TOML file.

        Args:
            config_path: Optional path to config file. Defaults to ~/.config/sentry/config.toml.

        Returns:
            Config instance with loaded values or defaults.

        Raises:
            ConfigError: If config file exists but cannot be parsed.
        """
        path = config_path or (Path.home() / ".config" / "sentry" / "config.toml")
        config = cls(config_path=path)

        if path.exists():
            try:
                with open(path, "rb") as f:
                    data = tomllib.load(f)
            except Exception as e:
                raise ConfigError(f"Failed to parse config file: {e}")

            # Load values from file
            if "thresholds" in data:
                thresholds = data["thresholds"]
                config.cpu_temp_threshold = thresholds.get(
                    "cpu_temp", config.cpu_temp_threshold
                )
                config.gpu_temp_threshold = thresholds.get(
                    "gpu_temp", config.gpu_temp_threshold
                )
                config.arm_voltage_min = thresholds.get(
                    "arm_voltage", config.arm_voltage_min
                )
                config.core_voltage_min = thresholds.get(
                    "core_voltage", config.core_voltage_min
                )

        return config

    def save(self) -> None:
        """Save configuration to TOML file.

        Creates the config directory if it doesn't exist.
        """
        self.config_path.parent.mkdir(parents=True, exist_ok=True)

        content = f"""# Sentry Configuration
# Generated by sentry config

[thresholds]
cpu_temp = {self.cpu_temp_threshold}
gpu_temp = {self.gpu_temp_threshold}
arm_voltage = {self.arm_voltage_min}
core_voltage = {self.core_voltage_min}
"""
        self.config_path.write_text(content)

    def validate(self) -> list[str]:
        """Validate configuration values.

        Returns:
            List of validation error messages (empty if valid).
        """
        errors = []
        if self.cpu_temp_threshold < 0 or self.cpu_temp_threshold > 100:
            errors.append("cpu_temp_threshold must be between 0 and 100")
        if self.gpu_temp_threshold < 0 or self.gpu_temp_threshold > 100:
            errors.append("gpu_temp_threshold must be between 0 and 100")
        if self.arm_voltage_min < 0.8 or self.arm_voltage_min > 1.5:
            errors.append("arm_voltage_min must be between 0.8 and 1.5")
        if self.core_voltage_min < 0.8 or self.core_voltage_min > 1.5:
            errors.append("core_voltage_min must be between 0.8 and 1.5")
        return errors


class ConfigError(Exception):
    """Configuration error exception."""

    pass
